version: '3.8'
services:
  web:
    build: 
      context: .
      target: dev
    restart: always
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    command: npm run dev

